name: tsitaat2

recipe: drupal8

config:
  webroot: web
  php: 7.2
  drush: 9.6.*

proxy:
  appserver:
    - local.tsitaat.com

services:
  appserver:
    xdebug: false
    run:
      - "echo 'Running composer install to initialize your project.'"
      - "cd /app && composer install"
  database:
    type: mariadb:10.2

events:
  post-db-import:
    - appserver: /app/.lando/post_db_import.sh
  post-start:
    - /app/.lando/post_start.sh

tooling:
  # As our webroot is a bit non-standard then we need to add --root parameter to Drush.
  drush:
    service: appserver
    cmd:
      - "drush --root=/app/web --uri=http://local.tsitaat.com/"
