name: tsitaat2

recipe: drupal8

config:
  webroot: web
  php: 7.2
  drush: 9.6.*

proxy:
  appserver:
    - local.tsitaat.com

services:
  appserver:
    xdebug: false
    run:
      - "echo 'Running composer install to initialize your project.'"
      - "cd /app && composer install"
  database:
    type: mariadb:10.2
  elasticsearch:
    type: compose
    services:
      image: blacktop/elasticsearch:6.4.0
      command: /elastic-entrypoint.sh elasticsearch
      # define port as "9200:9200" if you want to access directly in host.
      ports:
        - "9200"
  # Access Kibana at http://localhost:5601
  kibana:
    type: compose
    services:
      image: blacktop/kibana:6.4.0
      environment:
        KIBANA_ELASTICSEARCH_URL: http://elasticsearch:9200
      ports:
        - "5601:5601"
      command: /docker-entrypoint.sh kibana

events:
  post-db-import:
    - appserver: /app/.lando/post_db_import.sh
  post-start:
    - /app/.lando/post_start.sh

tooling:
  # As our webroot is a bit non-standard then we need to add --root parameter to Drush.
  drush:
    service: appserver
    cmd:
      - "drush --root=/app/web --uri=http://local.tsitaat.com/"
