name: tsitaat2

recipe: drupal8

config:
  webroot: web
  php: '7.2'
  drush: 9.6.2

proxy:
  appserver:
    - local.tsitaat.com

services:
  appserver:
    xdebug: true
    run:
      - "echo 'Running composer install to initialize your project.'"
      - "cd /app && composer install"
  database:
    type: mariadb:10.2
  # Create a node instance for theming.
  # @todo: This seemed big image. Should check for more light-weight versions from the official docker node page.
  node:
    type: node:8.14
    globals:
      gulp-cli: "latest"
    run-as-root:
      - "echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p"
      - npm install

events:
  post-db-import:
    - appserver: /app/.lando/post_db_import.sh
  post-start:
    - /app/.lando/post_start.sh

tooling:
  # As our webroot is a bit non-standard then we need to add --root parameter to Drush.
  drush:
    service: appserver
    cmd:
      - "drush --root=/app/web --uri=http://local.tsitaat.com/"
  npm:
    service: node
  gulp:
    description: Run gulp commands to build the theme. For ex use 'lando gulp build', 'lando gulp watch'...
    service: node
